@baseUrl=http://localhost:8080
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgwZDBmMjAxLWE3NzUtNGRiOS1hZWVkLTQ2M2NkMGRlNDkzOCJ9.L-qZsKHrAT-IO7HNi0rIkfd2PS9ogdQd5QxPjTlbnEM

### Create a new contact
POST {{baseUrl}}/contact
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "John",
  "last_name": "Doe",
  "phone_numbers": [
    {
      "number": "124-456-7890"
    },
    {
      "number": "989-654-3210"
    }
  ]
}

### Get all contacts
GET {{baseUrl}}/contact
Content-Type: application/json
Authorization: Bearer {{token}}

### Get a contact by id
GET {{baseUrl}}/contact/c3ccb1f2-e538-4b31-bdf2-53c38c6d0fd2
Content-Type: application/json
Authorization: Bearer {{token}}

### Update a contact
PUT {{baseUrl}}/contact/c3ccb1f2-e538-4b31-bdf2-53c38c6d0fd2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first_name": "Nana",
  "last_name": "Doe"
}

### Delete a contact
DELETE {{baseUrl}}/contact/c3ccb1f2-e538-4b31-bdf2-53c38c6d0fd2
Content-Type: application/json
Authorization: Bearer {{token}}

### add a phone number to a contact
POST {{baseUrl}}/contact/c3ccb1f2-e538-4b31-bdf2-53c38c6d0fd2/phone-number
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "number": "121-212-1212"
}

